var beyonce = ["Who run the world?","Pretty hurts.","Feeling like an animal with these cameras all in my grill.","This is how they made me.",
 "Took 45 minutes to get all dressed up.","Bow down, bitches.","My persuasion can build a nation.","We flawless, ladies tell 'em.",
 "I'm fresher than you.","I wanna leave my footprints on the sands of time.","Soul not for sale.","No angel.",
 "I'm feeling foxy.","World stop.... carry on.","Now put your hands up.","Makin' sure the DJ know what I want him to play.",
 "Boy this beat is crazy.","This my shit.","Tonight I'm not takin' no calls, 'cause I'll be dancin.","We're gonna turn this party out.",
 "People say that my, my style is so crazy.",
"I left my head and my heart on the dancefloor.","We ain't even gonna make it to this club.","I've been drinking, I've been drinking.",
"We woke up in the kitchen saying", "How the hell did this shit happen?.","Cause we like to party-y-y-y-y-y-y.","Diva is a female version of a hustla.",
"Private show with the music blastin'.","Welcome to Hollywood baby.","Smack that, clap, clap, clap like you don't care.",
"I'm singing on the mic til my voice hoarse.","Last thing I remember is our beautiful bodies grinding up in the club.","Yo nací para tus ojos, para nadie más.",
"Everywhere I'm looking now, I'm surrounded by your embrace.","Looking so crazy in love's, got me looking, got me looking so crazy in love.",
"If you liked it then you should have put a ring on it.","All I need in this life of sin, is me and my girlfriend.",
"I love the way you make me feel.","Down to ride 'til the very end, it's me and my boyfriend.",
"I woke up like this.","I'm feelin' myself.","***FLAWLESS.","I'm feelin' sexy.","I ain't no superstar.","I see your jealousy.","Hip hop star.","I think I'm ready.",
"You lookin' like you like what you see.","I wanna be myself tonight.","I'm a train wreck in the morning.","Gravity can't forget to pull me back to the ground again.",
"I know just what I'm wantin'.","I got beauty, I got class.","I wanna say I lived each day, until I die.","Beautiful nightmare.","I got gloss on my lips.","Speechless.",
"Me, myself, and I.","I got style and I got ass.","I stop the world.","Who run the world?","Pretty hurts.",
"My happiest moments weren't complete if you weren't by my side.","My baby is so damn sexy.","Your sexiness is so appealing, I can't let it go.","You'll do anything for me.",
"I miss you like every day.","Tell me, baby, why don't you love me?","Finally you put my love on top.","I love your face.","I know if I'm haunting you, you must be haunting me.",
"Drunk in love.","Your love is bright as ever, even in the shadows.","Take all of me.","Tattoo your name across my heart.", "I wanna hear you say my name boy.", 
"I think about you all the time, I see you in my dreams.",
"Feels so strange it feels so crazy to be in your world.","Lemme upgrade you."]