var foodie = ["I'm Only Here For The Free Food.","Anyone can sit here and buy you drinks. I want to buy you dinner!","Do people who go to the gym to 'feel the burn' know nothing of Mexican food?","I'm not a doctor but I know adding cheese to anything makes it an antidepressant.","I was never a photogenic person, because when everyone said cheese I said 'WHERE'?","My diet always starts on a Monday morning and ends at the donuts somebody brings into the office later that morning.","Remember: You can eat your way out of almost any problem.","Diet tip: If you think you're hungry, you might just be thirsty. Have a bottle of wine first and then see how you feel.","Me: 'sneaks out of the house' 'drives to another state' 'hides in a cave' 'quietly opens a bag of chips' My kids: Can we have some?","There is no love sincerer than the love of food. ",
"My annual performance review says I lack 'passion & intensity', guess management hasn't seen me alone with a Big Mac.","The dinner I was cooking for my family was going to be a surprise but the fire trucks ruined it.","Turning vegan is a big missed steak. ",
"I am on a seafood diet. Every time I see food, I eat it.","One day you're the best thing since sliced bread. The next, you're toast.","Entered what I ate today into my new fitness app and it just sent an ambulance to my house.","All you need is love. But a little chocolate now and then doesn't hurt. ",
"You are what what you eat eats.","The odds of going to the store for a loaf of bread and coming out with only a loaf of bread are three billion to one.","Food for the body is not enough. There must be food for the soul. ",
"Tell me what you eat, and I will tell you who you are.","I come from a family where gravy is considered a beverage.","Anything is good if it's made of chocolate. ",
"Animals are my friends… and I don't eat my friends.","I could talk food all day. I love good food.","There's no better feeling in the world than a warm pizza box on your lap.","Food is your body's fuel. Without fuel, your body wants to shut down.","The most dangerous food is wedding cake.","When I eat with my friends, it is a moment of real pleasure, when I really enjoy my life. ",
"The only think I like better than talking about Food is eating.","If food were free, why work?","Your diet is a bank account. Good food choices are good investments.","Food is for eating, and good food is to be enjoyed… I think food is, actually, very beautiful in itself.","I get way too much happiness from good food.","There's nothing more romantic than Italian food.","Every time you use the word 'healthy,' you lose. The key is to make yummy, delicious food that happens to be healthy.","I'm just someone who likes cooking and for whom sharing food is a form of expression.","I think about food literally all day every day. It's a thing. ",
"I think I was immediately fed, so food became a very important part of my life.","Food can be expressive and therefore food can be art.","Ice cream is my comfort food.","As long as there's pasta and Chinese food in the world, I'm okay.","I'm at the age where food has taken the place of sex in my life. In fact, I've just had a mirror put over my kitchen table.","I don't eat fast food, but I can't live without pizza.","People will travel anywhere for good food – it's crazy.","Not to like ice cream is to show oneself uninterested in food.","Real food, I've found, is actually better than dieting.","Patience is the secret to good food. ",
"If I can, I love staying in pajamas all day and watching movies and eating good food.","I was always a junk food person, still am.","I love pizza. I want to marry it, but it would just be to eat her family at the wedding.","If someone else is paying for it, food just tastes a lot better.","Eating good food is my favourite thing in the whole world. Nothing is more blissful.","If you combine good flavors, food turns into an orchestra.","Food is really and truly the most effective medicine.","You know, food is such – it's a hug for people.","The closest I've been to a diet this year is erasing food searches from my browser history.","My friends tell me that cooking is easy, but it's not easier than not cooking. "]
