var friends = ["Nobody has to like us, we like us.", "I will always have your back.","Yes, we know how obnoxious we are together. No, we don't care.",
"Three women walking outside by train tracks laughing","Friendship is born at that moment when one person says to another, 'What! You too? I thought I was the only one.'— C.S. Lewis",
"You can't sit with us.' — Mean Girls","When worst comes to worst, squad comes first.","You can't do epic sh't with basic people.",
"Group of women standing by a wall posing","The rest of the world was black and white, but we were in screaming color. — Taylor Swift",
"Find your tribe. Love them hard.","Friends who slay together, stay together.", "In squad we trust.","'I found out what the secret to life is — friends. Best friends.' — Fried Green Tomatoes",
"Three women wearing the same outfit taking a picture on a phone","'No man is a failure who has friends.' — It's a Wonderful Life",
"A good friend knows how you take your coffee. A great friend adds booze.","We all have that one friend who never learned how to whisper.",
"Finding friends with the same mental disorder: priceless!","I hope we're friends until we die. Then, I hope we stay ghost friends so we can walk through walls and scare the crap out of people together.",
"We will always be best friends, until we are old and senile. Then we can be new friends.","Just remember, if we get caught, you're deaf and I don't speak English.",
"Friendship is finding that special someone you can enjoy being a dumbass with.","We'll be the old ladies causing trouble in the nursing home.","Friends don't let friends do silly things alone.",
"We're more than friends. We're like a really small gang.","If I send you my ugly selfies, our friendship is real.","I'll even send you the snaps I look bad in.","Life is too short to be serious all the time. So, if you can't laugh at yourself, call me—I'll laugh at you.",
"Never let your friends feel lonely… disturb them all the time.","You drink too much. You cuss too much. You have questionable morals. You're everything I ever wanted in a friend.",
"True friends don't judge each other. They judge other people together.","Best friends don't care if your house is clean. They care if you have wine.", "Friends come and go like waves of the ocean, but the true ones stick like an octopus on your face.",
"You say I'm dirty-minded, but how did you understand what I meant?","Besides chocolate, you're my favorite.","Real friendship is when your friend comes over to your house just take a nap.",
"I love that I don't have to act socially acceptable around you.","I'd take a bullet for you—not in the head, but like the leg or something.","No one will ever be as entertained by us as us.","If you aren't somewhat crazy in the head, I'm afraid we can't be friends.",
"I appreciate the ones who are there at all times, not just when it's convenient.","You want to know who your true friends are? Screw up and see who's still there.","You know who your real friends are when you pull away from them and see who wonders why you are pulling away.",
"Some people talk to you in their free time and some people free their time to talk to you.","It's not about who's real to your face, it's about who stays real behind your back.","Only those who care about you can hear when you're quiet.","You'll know the people who feed your soul because you'll feel good after spending time with them.",
"As we grow up, we realize it's less important to have a ton of friends and more important to have real ones.",
"Real isn't who's with you at your celebration; real is who's standing next to you at rock bottom.","The only people I owe my loyalty to are those who never made me question theirs.","You should never have to think twice about who your real friends are.",
"Fake friends believe in rumors; real friends believe in you.","If someone seriously wants to be part of your life, they will make an effort to be in it. No reasons. No excuses.",
"I'm not going to tell you to get over it. I'm going to help you get through it.","The most memorable people in life will be the friends who loved you when you weren't very lovable.",
"F.R.I.E.N.D.S: Fight for you. Respect you. Include you. Encourage you. Need you. Deserve you. Stand by you.","A friend is one who overlooks your broken fence and admires the flowers in your garden.",
"Friendship isn't about who you've known the longest; it's about who walked into your life, said, 'I'm here for you,' and proved it.","There comes a time when you have to stop crossing oceans for people who wouldn't jump puddles for you.","I don't have time for part-time people in my life.",
"Friends: can I come over? Real friends: I'm coming over.","Lots of people misunderstand this word 'Friend;' it's a person who actually cares about you, not the things you've got or the things you can do for them.",
"They are not your friends until they have defended you in your absence.","The one who doesn't tell you what you want to hear but tells you what you need to hear… keep that.",
"Real isn't who's with you at your celebration; real is who's standing next to you at rock bottom.","The only people I owe my loyalty to are those who never made me question theirs.",
"You should never have to think twice about who your real friends are.","Fake friends believe in rumors; real friends believe in you.","If someone seriously wants to be part of your life, they will make an effort to be in it. No reasons. No excuses.",
"I'm not going to tell you to get over it. I'm going to help you get through it.","The most memorable people in life will be the friends who loved you when you weren't very lovable.",
"F.R.I.E.N.D.S: Fight for you. Respect you. Include you. Encourage you. Need you. Deserve you. Stand by you.","A friend is one who overlooks your broken fence and admires the flowers in your garden.",
"Friendship isn't about who you've known the longest; it's about who walked into your life, said, 'I'm here for you, and proved it.",
"There comes a time when you have to stop crossing oceans for people who wouldn't jump puddles for you.", "I don't have time for part-time people in my life.",
"Friends: can I come over? Real friends: I'm coming over.","Lots of people misunderstand this word 'Friend;' it's a person who actually cares about you, not the things you've got or the things you can do for them.",
"They are not your friends until they have defended you in your absence.","The one who doesn't tell you what you want to hear but tells you what you need to hear… keep that.",
"A real friend is like an angel who warms you by her presence and remembers you in her prayers.","Be with those who bring out the best in you, not the stress in you.",
"A friend is someone who can see the truth and pain in you, even when you're fooling everyone else.","Friends don't leave their friends for other friends.","Real friends don't tell you pretty lies. They tell you the ugly truth.",
"Side by side or miles apart, real friends are always close to the heart.","Don't lie to people who trust you and don't trust people who lie to you. Simple as that.","Friends pick us up when we fall down, and if they can't pick us up they lie down and listen for awhile.",
"Real friends get treated like family.","It's the friends you can call at 4 a.m. that matter.",
"True friendship is not about being inseparable—it is being separated and finding nothing changes.","A friend is one who listens, doesn't judge, and somehow makes everything all right.",
"Only trust someone who can see these three things: the sorrow behind your smile, the love behind your anger, and the reason behind your silence.","Time and good friends are two things that become more valuable the older you get.",
"Good friends show their love in times of trouble, not just in times of happiness.","Friendship isn't a big thing, it's a million little things." 
]